/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_davis_practice4android_jni_NMath */

#ifndef _Included_com_davis_practice4android_jni_NMath
#define _Included_com_davis_practice4android_jni_NMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_davis_practice4android_jni_NMath
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_davis_practice4android_jni_NMath_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_davis_practice4android_jni_NMath
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_davis_practice4android_jni_NMath_sub
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
